### ISSUE TITLE
.NET Install Tool for Extension Authors Dependency

### ISSUE THREAD

**Issue by sbhutch** [josetr/cmake-language-support#15]
This cmake language support extension looks great, but it has a dependency on ".NET Install Tool for Extension Authors". Is there a reason this needs to be installed on the host machine? It seems like a heavy-weight dependency and the extension appears to work despite not having .NET installed on the machine.

**Comment by josetr** [comment]
If it appears to work, you may be using https://marketplace.visualstudio.com/items?itemName=twxs.cmake.

CMake Language Support uses a Language Server that is 100% written in C# and therefore requires a .NET Runtime in order to run which is the reason why `.NET Install Tool for Extension Authors` needed.

**Comment by sbhutch** [comment]
You are right, I did have the twxs extension installed as well, but I was still getting far better syntax highlighting with your extension. Given your explanation, this issue is not valid and I will close it.

**Comment by josetr** [comment]
You are correct, syntax highlighting is one of the features that is partially implemented using the VSCode API, but it will only highlight a predefined set of commands / variables. Most features depend on the CMake Language Server that requires a .NET Runtime.
