### ISSUE TITLE
[Feature Request] Indent block statements (if, foreach, etc.)

### ISSUE THREAD

**Issue by Leopard20** [josetr/cmake-language-support#2]
It would be very nice if the extension automatically indented the statements inside if, foreach, etc. blocks.

**Comment by josetr** [comment]
Can you provide a gift showing the problem?

The current indentation is based on https://code.visualstudio.com/api/language-extensions/language-configuration-guide#indentation-rules and it should already be working.

Note that it isn't perfect tho as it's based on a simple regex pattern and I don't know how to tell the difference between `if(\nif` (where the 2nd `if` shouldn't increase the indentation level since its an argument and `if()\nif` where it should be.

The alternative is doing the indentation on the language server, but the `textDocument/onTypeFormatting` request is only sent if the user has the setting `Editor: Format On Type` enabled.

**Comment by josetr** [comment]
I've made some changes in the last version that may have fixed your problem. If not, I need a gif.

I've also added a new option `cmake.languageSupport.enableFileAPI` which is explained in https://marketplace.visualstudio.com/items?itemName=josetr.cmake-language-support-vscode. 

If you can try it out and let me know how it goes.
