### ISSUE TITLE
Is it possible to configure the formatting settings?

### ISSUE THREAD

**Issue by mdemoret-nv** [josetr/cmake-language-support#4]
Just wanted to start by saying thanks for making this extension. I've only been using it for 2 days and it's leaps and bounds better than the existing CMake language support extension.

I was wondering if it was possible to configure the formatting settings? Are you using another CMake formatting library? Formatting already works pretty well out of the box, but I want to get my entire team to use the same formatter to reduce diffs (which has been a problem for us). For other languages, we have used a config file (like `.clang-format`) to keep everyone on the same page. Is there something like this for your CMake extension?

**Comment by josetr** [comment]
> Just wanted to start by saying thanks for making this extension. I've only been using it for 2 days and it's leaps and bounds better than the existing CMake language support extension.

That was the goal and I'm glad you found it very useful!

> Are you using another CMake formatting library? 

No, we have our own.

> Formatting already works pretty well out of the box

This was the goal from the beginning. The formatter doesn't try to be too smart so that it works well for most people.

> I  was wondering if it was possible to configure the formatting settings?

It's not possible right now but it will be in the next release altho I cant give a release date because I'm a bit busy right now. Are you looking for a specific format setting that you want to change? if so, please let me know so that I can tell you if it's going to be available in the next update, and if it isn't, I will try to add it.

**Comment by mdemoret-nv** [comment]
> Are you looking for a specific format setting that you want to change?

Nothing in particular. Off the top of my mind: indent size, max line length (if wrapping is supported), and whether or not to add spaces around function parenthesis (i.e. `if (CONDITION)` vs. `if(CONDITION)`). Do you have a list of options that are coming in the next release? Would be interested to see whats in store

The main issue I'm having is that a colleague uses another IDE (CLion I think?) which has its own CMake formatting options. Depending on who formatted a file last, we might see a bunch of diffs in MRs just due to changing between formatting tools. So I was interested in whether or not you were using an external tool to see if there was a similar extension for his IDE. Otherwise, the best way forward is to choose the right options between formatting tools to minimize differences. From a quick glance, the 3 settings I listed above are the biggest cause of diffs between our two tools now.

**Comment by josetr** [comment]
* Indent size should already be working using `editor.insertSpaces`  and `editor.tabSize`.
* Spaces around function parenthesis can be added altho I may name it `SpaceAfterCommandName`.
* Max line length won't be initially supported.

**Comment by PavloCherniavskyi-tomtom** [comment]
In your interactive preview behavior is different:
`target_include_directories(multiple_server_queues_test
  PRIVATE
    ${CMAKE_CURRENT_SOURCE_DIR}`
Eventually PRIVATE has 2 spaces and CMAKE_CURRENT_SOURCE_DIR has 4.
But locally in target_include_directories I have 2 spaces indention for all target list. And can't find settings how to fix that. 

It would be nice to have more options so that extension could be more adjustable. At least some options in user/workspace settings.json could be added.

**Comment by lujomu** [comment]
I'd like to advocate for a setting that adds spaces **inside** parenthesis (as long as they are not empty).
E.g. `add_executable(MyTarget Source.cpp)` -> `add_executable( MyTarget Source.cpp )`

I am visually impaired and the spaces between tokens make code much easier to parse for my eyes.

**Comment by josetr** [comment]
I've updated the documentation with the newly added formatting options that should hopefully do what you guys were asking for.
